name: buildx

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: matthewhuie
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Build and push to Docker Hub
        run: |
          docker build --push \
            --tag matthewhuie/transmission:latest \
            --tag matthewhuie/transmission:$(git rev-parse --short HEAD) \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
